version: '3.7'

services:
  rentingsystem:
    container_name: rentingsystem
    image: ${DOCKER_REGISTRY-}rentingsystem
    build:
      context: .
      dockerfile: RentingSystem/Dockerfile
    depends_on:
        - DataBaseSQL
        - rentingsystemapi
    environment:
        - API_URL=rentingsystemapi:8000
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "3000:80"
        - "3001:443"
   
  rentingsystemapi:
    container_name: rentingsystemapi
    image: ${DOCKER_REGISTRY-}rentingsystemapi
    build:
      context: .
      dockerfile: RentingSystemAPI/Dockerfile
    depends_on:
        - DataBaseSQL
    environment:
       - DBServer=DataBaseSQL
    ports:
        - "8000:80"
        - "8001:443"

  DataBaseSQL:
    container_name: DataBaseSQL
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Password2020
    ports:
        - "1433:1433"
    volumes:
        - ./Database:/var/opt/mssql/bak
    
volumes:
    DataBase:         