version: '3.7'

services:
  rentingsystem:
    container_name: rentingsystem
    image: ${DOCKER_REGISTRY-}rentingsystem
    build:
      context: .
      dockerfile: RentingSystem/Dockerfile
    depends_on:
        - DataBaseSQL
        - rentingsystemapi
    ports:
        - "3000:80"
        - "3001:443"
    networks:
        - net
    
  rentingsystemapi:
    container_name: rentingsystemapi
    image: ${DOCKER_REGISTRY-}rentingsystemapi
    build:
      context: .
      dockerfile: RentingSystemAPI/Dockerfile
    depends_on:
        - DataBaseSQL
    environment:
        DBServer: DataBaseSQL
    ports:
        - "8000:80"
        - "8001:443"
    networks:
        - net

  DataBaseSQL:
    container_name: DataBaseSQL
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Password2020
    ports:
        - "1433:1433"
    volumes:
        - ./DataBase:/var/opt/mssql/bak
    networks:
        - net

volumes:
    DataBase:
networks:
    net: