version: '2'

services:
  DataBaseSQL:
    container_name: DataBaseSQL
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: Password2020
    ports:
        - "1433:1433"
    volumes:
        - ./DatabaseBackUp:/var/opt/mssql/bak
    restart: unless-stopped
    healthcheck:
        test: "exit 0"

  rentingsystem:
    container_name: rentingsystem
    image: ${DOCKER_REGISTRY-}rentingsystem
    build:
      context: .
      dockerfile: RentingSystem/Dockerfile
    depends_on:
        DataBaseSQL:
            condition: service_healthy
        rentingsystemapi:
            condition: service_started

    environment:
        - API_URL=rentingsystemapi:8000
        - ASPNETCORE_ENVIRONMENT=development
    ports:
        - "3000:80"
        - "3001:443"
    restart: unless-stopped
   
  rentingsystemapi:
    container_name: rentingsystemapi
    image: ${DOCKER_REGISTRY-}rentingsystemapi
    build:
      context: .
      dockerfile: RentingSystemAPI/Dockerfile
    depends_on:
        DataBaseSQL:
            condition: service_healthy
    environment:
       - DBServer=DataBaseSQL
       - ASPNETCORE_ENVIRONMENT=development
    ports:
        - "8000:80"
        - "8001:443"
    restart: unless-stopped

volumes:
    DataBase:         